services:
  - type: web
    name: LeZwuen
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: DATABASE_SSL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_BASE_URL
        sync: false
